### ISSUE TITLE
Received 

### ISSUE THREAD

**Issue by xeryx01** [BattletechModders/IRBTModUtils#1]
Had this pop up in command console while running IRBT and the Clevergirl, not sure exactly when the error occurred but here is the log.

[errorBT_output_log.txt](https://github.com/IceRaptor/IRBTModUtils/files/4269428/errorBT_output_log.txt)

**Comment by xeryx01** [comment]
![20200227132803_1](https://user-images.githubusercontent.com/45599120/75593206-dae47200-5a41-11ea-85e9-b1a0536f8e7f.jpg)

**Comment by IceRaptor** [comment]
This is actually an error between gnivler's [panic system](https://github.com/gnivler/PanicSystem/) and my IRBTModUtils code. He re-used my code without changing some of the enum values, which causes this issue. Gnivler no longer seems to be maintaining his code, so I forked his code into https://github.com/BattletechModders/PanicSystem and made the fix myself. If you're using his PanicSystem and IRBTModUtils together, I'd strongly suggest getting the updated version from BTModders. It should eliminate this error entirely.
