### ISSUE TITLE
Missing .dll for both 1.6.3 and 1.6.1

### ISSUE THREAD

**Issue by cescudero95** [BattletechModders/IRBTModUtils#2]
The .dll for this mod appears to be missing.  Same issue when I tried 1.6.3 recently.

IRBTModUtils 1.6.1
Expanding manifest IRBTModUtils:
	:StreamingAssets
	Error: DLL specified (C:\SteamLibrary\steamapps\common\BATTLETECH\Mods\IRBTModUtils-REL_1.6.1\IRBTModUtils.dll), but it's missing! Aborting load.

Same error in log for both (modtek log).  I don't see the .dll anywhere, any ideas?

**Comment by IceRaptor** [comment]
I just checked and both downloads include the files - https://github.com/IceRaptor/IRBTModUtils/releases/download/REL_1.6.3/IRBTModUtils-1.6.3.zip has it, as shown in

![image](https://user-images.githubusercontent.com/96743/77982201-be09bb80-72d9-11ea-9fdb-e33d62894d8c.png)

Perhaps your zip corrupted when it was loaded? Also, you might try renaming the folder to just IRBTModUtils - I don't know if Modtek has weirdnesses with hyphens or dashes in the name.

**Comment by cescudero95** [comment]
Thanks, I had the same issue with CBTBehaviors

I was downloading the zip multiple times from your 'Releases' page for each of these mods.  Is that a different link you shared?

**Comment by IceRaptor** [comment]
Yes, that link is from the releases page. I downloaded both 1.6.3 and 1.6.1 and extracted them on my PC, and then checked the contents. You can see from the screenshot the file is present - so I'm not sure what is going on. I'm guessing ModTek may not like the hyphens in the name, but that's a wild-ass guess with nothing backing it up.

**Comment by cescudero95** [comment]
Interesting, not sure.  It hasn't happened for all mods but a couple of other mods have had missing .dlls.  When you gave me the link here it worked, and the mod is now functioning.  Could you provide the .dll for CBTBehaviors possibly?  I'm using the non-enhanced one, for vanilla (no MechEngineer)

**Comment by EricAKAPode** [comment]
Very excited to try Concrete Jungle, saw you updated this to support it, but no .dll for 1.64. My coding is not up to the task of compiling from source. Some help?

**Comment by IceRaptor** [comment]
Updated the release tag to have the 1.6.4 binary. Sorry for the delay!
